# Generated by Django 5.1.4 on 2024-12-30 05:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EcommerceUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=40, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("given_name", models.CharField(max_length=40)),
                ("family_name", models.CharField(max_length=40)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "default_permissions": ("add", "change", "view"),
                "permissions": [("vendor_status", "売り手です")],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="info",
            field=models.CharField(
                blank=True, help_text="商品の詳細", max_length=3000, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("f", "販売中"), ("s", "販売済み"), ("c", "販売確定")],
                default="f",
                help_text="商品の販売ステータス",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="全商品の中にこの商品の一意の識別子",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                default="商品名未定義", help_text="商品名を入力してください", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
