# Generated by Django 5.1.4 on 2025-01-29 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_rename_user_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
    ]
