# Generated by Django 5.1.4 on 2025-02-08 03:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_alter_customuser_family_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="商品の一意の識別子",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                default="商品名未定義", max_length=200, verbose_name="商品名"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("f", "販売中"), ("s", "販売済み"), ("c", "販売確定")],
                default="f",
                help_text="商品の販売ステータス",
                max_length=1,
                verbose_name="販売ステータス",
            ),
        ),
    ]
