# Generated by Django 5.1.4 on 2025-02-08 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "default_permissions": ("add", "change", "view"),
                "permissions": [("vendor_status", "売り手です")],
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
            },
        ),
    ]
