# Generated by Django 5.1.4 on 2025-02-16 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="作成日時"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("f", "販売中"), ("s", "販売済み"), ("c", "販売確定")],
                default="f",
                max_length=1,
                verbose_name="販売ステータス",
            ),
        ),
    ]
