# Generated by Django 5.1.4 on 2025-02-20 06:19

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to=catalog.models.user_image_directory_path),
        ),
    ]
