# Generated by Django 5.1.4 on 2025-02-20 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_alter_image_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "画像", "verbose_name_plural": "画像"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [("vendor_status", "売り手です")],
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
            },
        ),
    ]
