# Generated by Django 5.1.4 on 2025-03-20 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_alter_image_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
            ),
        ),
    ]
